'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'

type SupportedLanguage = 'en' | 'es' | 'de'
type LanguagePreference = 'device' | SupportedLanguage

type LanguageContextValue = {
  preference: LanguagePreference
  language: SupportedLanguage
  setPreference: (pref: LanguagePreference) => void
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

function resolveDeviceLanguage(): SupportedLanguage {
  if (typeof navigator === 'undefined') return 'en'
  const lang = navigator.language.toLowerCase()
  if (lang.startsWith('es')) return 'es'
  if (lang.startsWith('de')) return 'de'
  if (lang.startsWith('en')) return 'en'
  return 'en'
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [preference, setPreferenceState] = useState<LanguagePreference>('device')
  const [language, setLanguage] = useState<SupportedLanguage>('en')

  useEffect(() => {
    if (typeof window === 'undefined') return
    const stored = window.localStorage.getItem('shiftcoach:language')
    const pref: LanguagePreference =
      stored === 'device' || stored === 'en' || stored === 'es' || stored === 'de'
        ? (stored as LanguagePreference)
        : 'device'
    setPreferenceState(pref)
    setLanguage(pref === 'device' ? resolveDeviceLanguage() : pref)
  }, [])

  const setPreference = (pref: LanguagePreference) => {
    setPreferenceState(pref)
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('shiftcoach:language', pref)
    }
    setLanguage(pref === 'device' ? resolveDeviceLanguage() : pref)
  }

  const value = useMemo(
    () => ({
      preference,
      language,
      setPreference,
    }),
    [preference, language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return ctx
}

// Simple in-memory translation table for core UI strings.
const messages: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.calendar': 'Calendar',
    'nav.blog': 'Blog',
    'nav.browse': 'Browse',
    'nav.profile': 'Profile',

    'browse.title': 'Browse',
    'browse.subtitle': 'Jump straight to the tools you need.',
    'browse.sleepLog.title': 'Sleep Log',
    'browse.sleepLog.desc': 'View and edit your recent sleep.',
    'browse.activity.title': 'Activity',
    'browse.activity.desc': 'Log steps and activity for your shifts.',
    'browse.shiftCoach.title': 'Shift Coach',
    'browse.shiftCoach.desc': 'Ask the AI coach for tailored tips.',
    'browse.settings.title': 'Settings',
    'browse.settings.desc': 'Update profile, units and app preferences.',
    'browse.wearables.title': 'Wearables',
    'browse.wearables.desc': 'Connect your Apple or Samsung watch.',
    'browse.feedback.title': 'Report a problem',
    'browse.feedback.desc': 'Send feedback or report a bug.',

    'settings.title': 'Settings',
    'settings.section.account': 'Account',
    'settings.section.preferences': 'Preferences',
    'settings.section.coaching': 'Coaching',
    'settings.section.support': 'Support',

    'settings.language.title': 'Language',
    'settings.language.device': 'Use device language',
    'settings.language.en': 'English',
    'settings.language.es': 'Spanish',
    'settings.language.de': 'German',

    'splash.tagline': "The only app dedicated to shift workers' health and wellbeing",
    'splash.audience': 'Built with nurses, paramedics, guards, chefs and operators in mind.',
    'splash.preparing': 'Preparing your shift plan…',
    'splash.imageAlt': 'Group of shift workers',

    'auth.tagline': 'Dedicated to shift worker health and wellbeing.',
    'auth.personalized': 'Personalized for your shifts',
    'auth.signIn.title': 'Welcome',
    'auth.signIn.subtitle': 'Sign in to continue your plan.',
    'auth.signIn.email': 'Email',
    'auth.signIn.password': 'Password',
    'auth.signIn.submit': 'Sign In',
    'auth.signIn.busy': 'Signing in…',
    'auth.signIn.forgotPassword': 'Forgot password?',
    'auth.signIn.noAccount': 'No account?',
    'auth.signIn.createOne': 'Create one',
    'auth.signIn.errorInvalid': 'Invalid email or password. Please check your credentials and try again.',
    'auth.signIn.errorNetwork': 'Network error. Please check your internet connection and try again.',
    'auth.signIn.errorGeneric': 'An error occurred during sign in. Please try again.',
    'auth.signIn.errorConnect': 'Unable to connect to the server. Please check your internet connection and ensure Supabase is reachable.',
    'auth.signIn.errorUnexpected': 'An unexpected error occurred. Please try again.',
    'auth.signIn.loading': 'Loading…',
    'auth.signIn.configError': 'Configuration error: Supabase URL is missing. Please check your .env.local file.',

    'auth.signUp.title': 'Create account',
    'auth.signUp.titleConfirm': 'Check your email',
    'auth.signUp.subtitle': 'Start your journey to better shift work health.',
    'auth.signUp.email': 'Email',
    'auth.signUp.password': 'Password',
    'auth.signUp.passwordHint': 'Must be at least 6 characters',
    'auth.signUp.submit': 'Sign Up',
    'auth.signUp.busy': 'Creating…',
    'auth.signUp.hasAccount': 'Already have an account?',
    'auth.signUp.signIn': 'Sign in',
    'auth.signUp.confirmTitle': 'Confirmation email sent!',
    'auth.signUp.confirmBody': "Please check your email and click the confirmation link to continue. You'll be redirected to set up your profile.",
    'auth.signUp.noEmail': "Didn't receive the email? Check your spam folder or",
    'auth.signUp.tryAgain': 'try again',
    'auth.signUp.alreadyConfirmed': 'Already confirmed? Sign in',
    'auth.signUp.loading': 'Preparing sign-up…',

    'onboarding.title': 'Welcome to ShiftCoach',
    'onboarding.subtitle': "Let's set up your profile",
    'onboarding.stepOf': 'Step {step} of {total}',
    'onboarding.name': 'Name',
    'onboarding.namePlaceholder': 'Enter your name',
    'onboarding.gender': 'Gender',
    'onboarding.male': 'Male',
    'onboarding.female': 'Female',
    'onboarding.other': 'Other',
    'onboarding.dateOfBirth': 'Date of Birth',
    'onboarding.optional': '(optional)',
    'onboarding.age': 'Age',
    'onboarding.agePlaceholder': 'Enter your age',
    'onboarding.dobHint': 'You must be at least 13 years old',
    'onboarding.ageRange': 'Must be between 13 and 120',
    'onboarding.validation.ageRange': 'Age must be between 13 and 120',
    'onboarding.validation.dobMin': 'You must be at least 13 years old',
    'onboarding.validation.ageMin': 'Age must be at least 13',
    'onboarding.validation.ageMax': 'Age must be 120 or less',
    'onboarding.validation.ageMismatch': "Age doesn't match date of birth (should be around {age})",
    'onboarding.units': 'Measurement units',
    'onboarding.metric': 'Metric (cm, kg)',
    'onboarding.imperial': 'Imperial (ft/in)',
    'onboarding.heightCm': 'Height (cm)',
    'onboarding.heightCmPlaceholder': '175',
    'onboarding.height': 'Height',
    'onboarding.feet': 'Feet',
    'onboarding.inches': 'Inches',
    'onboarding.weight': 'Weight',
    'onboarding.stone': 'Stone',
    'onboarding.pounds': 'Pounds',
    'onboarding.validation.heightCm': 'Height must be between 100cm and 250cm',
    'onboarding.validation.heightCmHint': 'Enter your height in centimeters',
    'onboarding.validation.heightBoth': 'Please enter both feet and inches',
    'onboarding.validation.heightRange': 'Height must be between 3ft 3in and 8ft 2in',
    'onboarding.validation.heightHint': 'Enter your height in feet and inches',
    'onboarding.validation.weightRange': 'Weight must be between 30kg and 300kg (66-660 lbs)',
    'onboarding.validation.weightKg': 'Weight must be between 30kg and 300kg',
    'onboarding.validation.weightLb': 'Weight must be between 66lbs and 660lbs',
    'onboarding.goal': 'Goal',
    'onboarding.lose': 'Lose',
    'onboarding.maintain': 'Maintain',
    'onboarding.gain': 'Gain',
    'onboarding.sleepGoal': 'Sleep goal (hours)',
    'onboarding.validation.sleepRange': 'Sleep goal must be between 4 and 12 hours',
    'onboarding.sleepHint': 'Recommended: 7–9 hours for adults',
    'onboarding.waterGoal': 'Water goal (L)',
    'onboarding.validation.waterRange': 'Water goal must be between 1.0L and 5.0L',
    'onboarding.waterHint': 'Recommended: 2.0–3.0L per day based on scientific guidelines',
    'onboarding.back': 'Back',
    'onboarding.continue': 'Continue',
    'onboarding.complete': 'Complete Setup',
    'onboarding.saving': 'Saving…',
    'onboarding.loading': 'Loading…',
    'onboarding.saveFailed': 'Failed to save profile',
    'onboarding.networkError': 'Network error. Please check your connection.',

    'welcome.title': 'Your plan is ready',
    'welcome.subtitle': 'Based on your profile, goals and shift work pattern.',
    'welcome.personalisedTarget': 'Personalised daily target',
    'welcome.kcalPerDay': 'kcal / day',
    'welcome.basedOn': 'Based on your height, weight, age, goal and the demands of shift work, this is what ShiftCoach recommends for',
    'welcome.standardWouldGive': 'A standard calculator would give you around',
    'welcome.weAdjusted': "We've adjusted by",
    'welcome.forPatterns': 'for your sleep, shifts and recent patterns.',
    'welcome.shiftAdjustedCalories': 'Shift‑adjusted calories',
    'welcome.shiftAdjustedCaloriesDesc': 'Built specifically for rotating days, nights and long runs.',
    'welcome.timingAware': 'Timing aware',
    'welcome.timingAwareDesc': 'We nudge more calories into the parts of your shift that need it.',
    'welcome.hydrationGuidance': 'Hydration guidance',
    'welcome.hydrationGuidanceDesc': 'Daily water targets tuned to long and overnight shifts.',
    'welcome.nextStep': "Next: see today's plan with meal timing, macros and energy curve.",
    'welcome.continueToDashboard': 'Continue to dashboard',
    'welcome.loading': 'Loading...',
    'welcome.todayNight': "Tonight's night shift",
    'welcome.todayOff': 'Today (Day Off)',
    'welcome.todayDay': "Today's day shift",
    'welcome.today': 'Today',

    'dashboard.loading': 'Preparing your ShiftCoach dashboard…',
    'dashboard.homeLabel': 'Home',
    'dashboard.wearable.connected': 'Connected',
    'dashboard.wearable.notConnected': 'Not connected',
    'dashboard.wearable.tapToConnect': 'Tap to connect',
    'dashboard.wearable.syncing': 'Syncing…',
    'dashboard.wearable.synced': 'Synced',
    'dashboard.wearable.errorDenied': 'Connection denied',
    'dashboard.wearable.errorServer': 'Server not configured',
    'dashboard.wearable.errorRedirect': 'Redirect URI mismatch',
    'dashboard.wearable.errorToken': 'Token exchange failed',
    'dashboard.wearable.errorGeneric': "Couldn't connect",
    'dashboard.bodyClock.comingSoon': 'Body clock score coming soon',
    'dashboard.bodyClock.stronglyAligned': 'Your body clock is strongly aligned',
    'dashboard.bodyClock.inSync': 'Your body clock is in sync',
    'dashboard.bodyClock.slightlyOut': 'Your body clock is slightly out of sync',
    'dashboard.bodyClock.outOfSync': 'Your body clock is out of sync',
    'dashboard.bodyClock.unlockHint': 'Log a few nights of sleep and add your shifts to unlock your Body Clock score.',
    'dashboard.bodyClock.calculatedFrom': 'Calculated from your recent sleep, rota pattern and light timing over the last few days.',
    'dashboard.bodyClock.openAria': 'Open Body Clock page',
    'dashboard.lastSync.notYet': 'Last sync: not yet',
    'dashboard.lastSync.justNow': 'Last sync: just now',
    'dashboard.lastSync.minAgo': 'Last sync: {n} min ago',
    'dashboard.lastSync.hAgo': 'Last sync: {n} h ago',
    'dashboard.lastSync.dayAgo': 'Last sync: {n} day ago',
    'dashboard.lastSync.daysAgo': 'Last sync: {n} days ago',
    'dashboard.shiftLabel.night': 'Night shift',
    'dashboard.shiftLabel.day': 'Day shift',
    'dashboard.shiftLabel.dayOff': 'Day off',
    'dashboard.shiftLabel.late': 'Late shift',
    'dashboard.shiftLabel.shift': 'Shift',
    'dashboard.rhythm': 'Rhythm',
    'dashboard.recovery.calculating': 'Calculating recovery…',
    'dashboard.recovery.calculatingMessage': "We're combining your latest sleep and movement to score your recovery for today.",
    'dashboard.recovery.unavailable': 'Recovery score unavailable',
    'dashboard.recovery.notScored': 'Recovery not scored yet',
    'dashboard.recovery.notScoredMessage': 'Log some sleep and sync your wearables to see a daily recovery score here.',
    'dashboard.recovery.recovered': 'Recovered',
    'dashboard.recovery.recoveredMessage': 'Sleep and movement are supporting recovery today – this is a good day for tougher shifts or training.',
    'dashboard.recovery.okNotCharged': 'OK, not fully charged',
    'dashboard.recovery.okMessage': "You're not running on empty, but slightly under‑recovered. Protect sleep tonight and keep activity moderate.",
    'dashboard.recovery.runningLow': 'Running low',
    'dashboard.recovery.runningLowMessage': 'Recovery is low – prioritise sleep, lighter shifts where possible and avoid stacking back‑to‑back nights.',
    'dashboard.shiftLag.low': 'Low',
    'dashboard.shiftLag.mod': 'Mod',
    'dashboard.shiftLag.high': 'High',
    'dashboard.shiftLag.per100': '/100',
    'dashboard.mealTimes.title': 'Meal Times',
    'dashboard.mealTimes.night': 'Night',
    'dashboard.mealTimes.day': 'Day',
    'dashboard.mealTimes.late': 'Late',
    'dashboard.mealTimes.off': 'Off',
    'dashboard.mealTimes.whyAria': 'Why meal timing matters',
    'dashboard.mealTimes.closeAria': 'Close',
    'dashboard.mealTimes.closeStatus': 'Close',
    'dashboard.mealTimes.whyTitle': 'Why Meal Timing Matters',
    'dashboard.mealTimes.notLogged': 'Not logged',
    'dashboard.mealTimes.onTime': 'On time',
    'dashboard.mealTimes.logged': 'Logged',
    'dashboard.bodyClockInfo.title': 'How your Body Clock score works',
    'dashboard.bodyClockInfo.closeAria': 'Close body clock info',

    'detail.common.backToDashboard': 'Back to dashboard',
    'detail.common.loading': 'Loading…',
    'detail.common.noData': 'No data',
    'detail.common.disclaimer': 'A coaching app only and does not replace medical advice. Please speak to a healthcare professional about any health concerns.',
    'detail.common.goToDashboard': 'Go to Dashboard',

    'detail.bodyClock.title': 'Body clock',
    'detail.bodyClock.scoreLabel': 'Body clock score',
    'detail.bodyClock.overLast7': 'Body clock over last 7 days',
    'detail.bodyClock.higherBars': 'Higher bars = days your body clock was more in rhythm with your shifts.',
    'detail.bodyClock.patternVsRecovery': 'Shift pattern vs recovery',
    'detail.bodyClock.patternStable': 'Pattern: mostly stable',
    'detail.bodyClock.patternHeavy': 'Pattern: heavy strain week',
    'detail.bodyClock.patternChoppy': 'Pattern: choppy week',
    'detail.bodyClock.patternMixed': 'Pattern: mixed',
    'detail.bodyClock.patternExplanation': 'This looks at how many days your body clock score dipped below the in‑sync range. Runs of nights, very short turnarounds or long commutes can pull several days down in a row.',
    'detail.bodyClock.sleepTiming': 'Sleep timing consistency',
    'detail.bodyClock.timingNoData': 'Not enough sleep timing data yet.',
    'detail.bodyClock.timingRegular': 'Your main sleep has been fairly regular this week.',
    'detail.bodyClock.timingShifting': 'Sleep timing is shifting around – watch late finishes and early starts close together.',
    'detail.bodyClock.timingFlipped': 'Sleep timing has been flipped or very irregular – your body clock is working hard to keep up with shifts.',
    'detail.bodyClock.timingTip': 'Try to keep at least 3 nights in a row with similar main‑sleep timing on off‑days so your body clock can catch up between heavy runs of shifts.',
    'detail.bodyClock.lightHabits': 'Light habits that protect your clock',
    'detail.bodyClock.lightDay': 'Day shifts: aim for 15–20 minutes of outside light most days.',
    'detail.bodyClock.lightNight': 'Night shifts: wear sunglasses on the way home and keep the bedroom dark.',
    'detail.bodyClock.lightEvening': 'Evenings off: dim screens and bright lights 1–2 hours before planned sleep.',
    'detail.bodyClock.riskWindow': 'Upcoming risk window',
    'detail.bodyClock.riskWindowText': "Based on this week's pattern, your body clock will find runs of nights, early starts and short turnarounds hardest. Treat the days after these blocks as recovery shifts: protect sleep, keep caffeine early and keep meals lighter overnight.",
    'detail.bodyClock.waitingData': 'Waiting for enough sleep and shift data to show your 7‑day body clock trend.',
    'detail.bodyClock.warningMixed': 'Mixed week – keep an eye on runs of nights and very short sleeps.',
    'detail.bodyClock.warningStable': 'Your body clock has mostly stayed in rhythm this week – keep protecting recovery days.',
    'detail.bodyClock.warningOutOfSync': "Your body clock has been out of sync on most days – treat upcoming days as recovery where you can and check your rota pattern.",
    'detail.bodyClock.warningQuiteFew': 'Quite a few days out of rhythm – watch stretches of nights, early starts and broken sleep.',

    'detail.shiftRhythm.title': 'Shift Rhythm',
    'detail.adjustedCalories.title': 'Adjusted Calories',
    'detail.heartHealth.title': 'Heart Health',
    'detail.hydration.title': 'Hydration',
    'detail.bingeRisk.title': 'Binge Risk',
    'detail.shiftLag.title': 'Shift Lag',
    'detail.recovery.title': 'Recovery Score',
    'detail.recovery.subtitle': 'How ready your body and mind are for your next shift',
    'detail.wearablesSetup.title': 'Connect your wearable',
    'detail.wearablesSetup.howReadsData': 'How ShiftCoach reads your data',
    'detail.wearablesSetup.intro1': "ShiftCoach doesn't talk directly to your watch. Instead it reads steps, sleep and activity from the health app on your phone that your watch is already syncing to.",
    'detail.wearablesSetup.intro2': "Choose your device below and we'll show you simple, device‑specific steps to get set up.",
    'detail.wearablesSetup.appleWatch': 'Apple Watch',
    'detail.wearablesSetup.appleWatchDesc': 'Uses Apple Health on your iPhone',
    'detail.wearablesSetup.samsungAndroid': 'Samsung / Android watch',
    'detail.wearablesSetup.samsungAndroidDesc': 'Uses Samsung Health + Health Connect',
    'detail.wearablesSetup.otherWearable': 'Other wearable (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherWearableDesc': "For now, connect via your phone's health apps",
    'detail.wearablesSetup.stepsApple': 'Steps for Apple Watch',
    'detail.wearablesSetup.appleStep1': 'Make sure your watch is paired with your iPhone and Apple Health is turned on in the Watch app.',
    'detail.wearablesSetup.appleStep2': 'Open the Health app on your phone and check that it shows your steps and sleep.',
    'detail.wearablesSetup.appleStep3': 'In ShiftCoach, go to Settings → Sync wearables (or the sync button on the home screen) and follow the prompts when "Connect Apple Health" is available.',
    'detail.wearablesSetup.appleBeta': 'For the current beta, Apple Watch data will appear once HealthKit support is enabled in the App Store version of ShiftCoach.',
    'detail.wearablesSetup.stepsSamsung': 'Steps for Samsung / Android watches',
    'detail.wearablesSetup.samsungStep1': 'Open Samsung Health on your phone and go to Settings → Connected services.',
    'detail.wearablesSetup.samsungStep2': 'Connect Health Connect and turn on syncing for Steps (and sleep if available).',
    'detail.wearablesSetup.samsungStep3': 'Make sure your watch app (for example Samsung Health) is writing activity into Health Connect.',
    'detail.wearablesSetup.samsungStep4': 'In ShiftCoach, tap the "Sync wearables" button on the dashboard and sign in with the same Google account.',
    'detail.wearablesSetup.samsungDone': 'Once this is done, ShiftCoach will automatically pull your steps and sleep from Health Connect when you open the app.',
    'detail.wearablesSetup.otherTitle': 'Other wearables (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherP1': 'In future versions we\'ll add direct connections for more brands. For now, the easiest way is to sync your device into Apple Health or Health Connect on your phone, then let ShiftCoach read from there.',
    'detail.wearablesSetup.otherP2': 'Many apps (including Fitbit and Garmin) can write steps and sleep into these health hubs in their own settings.',
    'detail.wearablesSetup.whatYouGet': "What you get once it's connected",
    'detail.wearablesSetup.benefit1': 'Automatic steps and movement on your home screen and Activity page.',
    'detail.wearablesSetup.benefit2': 'More accurate sleep and Shift Lag scores based on real nights, not guesses.',
    'detail.wearablesSetup.benefit3': 'Better calorie and recovery targets that reflect how hard your actual shifts are.',
    'detail.wearablesSetup.readyToSync': 'Ready to sync your wearable?',
    'detail.wearablesSetup.tapBelow': "Tap below after you've followed the steps for your device.",
    'detail.wearablesSetup.statusConnected': 'Wearable connected',
    'detail.wearablesSetup.statusConnectedDesc': 'Your wearable is linked. Tap sync to pull the latest steps and sleep.',
    'detail.wearablesSetup.verifiedWorking': 'Connection verified – your watch data is reaching ShiftCoach.',
    'detail.wearablesSetup.stepsToday': 'Steps today: {count}',
    'detail.wearablesSetup.verifiedConfirmation': 'Your wearable is connected and working. Steps and sleep will appear on the dashboard after sync.',
    'detail.wearablesSetup.statusNotConnected': 'Wearable not connected',
    'detail.wearablesSetup.notConnectedWhy': "ShiftCoach needs wearable access to read your watch's steps and sleep. Connect Samsung Health (or your watch app) to Health Connect on Android, or Apple Health on iPhone.",
    'detail.wearablesSetup.connectGoogleFit': 'Open wearable setup',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.calendar': 'Calendario',
    'nav.blog': 'Blog',
    'nav.browse': 'Explorar',
    'nav.profile': 'Perfil',

    'browse.title': 'Explorar',
    'browse.subtitle': 'Ve directo a las herramientas que necesitas.',
    'browse.sleepLog.title': 'Registro de sueño',
    'browse.sleepLog.desc': 'Revisa y edita tu sueño reciente.',
    'browse.activity.title': 'Actividad',
    'browse.activity.desc': 'Registra pasos y actividad para tus turnos.',
    'browse.shiftCoach.title': 'Shift Coach',
    'browse.shiftCoach.desc': 'Pregunta al coach de IA por consejos a medida.',
    'browse.settings.title': 'Ajustes',
    'browse.settings.desc': 'Actualiza perfil, unidades y preferencias.',
    'browse.wearables.title': 'Wearables',
    'browse.wearables.desc': 'Conecta tu reloj Apple o Samsung.',
    'browse.feedback.title': 'Informar un problema',
    'browse.feedback.desc': 'Envía comentarios o informa un error.',

    'settings.title': 'Ajustes',
    'settings.section.account': 'Cuenta',
    'settings.section.preferences': 'Preferencias',
    'settings.section.coaching': 'Entrenamiento',
    'settings.section.support': 'Soporte',

    'settings.language.title': 'Idioma',
    'settings.language.device': 'Usar idioma del dispositivo',
    'settings.language.en': 'Inglés',
    'settings.language.es': 'Español',
    'settings.language.de': 'Alemán',

    'splash.tagline': 'La única app dedicada a la salud y el bienestar de los trabajadores por turnos',
    'splash.audience': 'Pensada para enfermeras, paramédicos, guardias, chefs y operarios.',
    'splash.preparing': 'Preparando tu plan de turnos…',
    'splash.imageAlt': 'Grupo de trabajadores por turnos',

    'auth.tagline': 'Dedicada a la salud del trabajador por turnos.',
    'auth.personalized': 'Personalizado para tus turnos',
    'auth.signIn.title': 'Bienvenido de nuevo',
    'auth.signIn.subtitle': 'Inicia sesión para continuar con tu plan.',
    'auth.signIn.email': 'Correo electrónico',
    'auth.signIn.password': 'Contraseña',
    'auth.signIn.submit': 'Iniciar sesión',
    'auth.signIn.busy': 'Iniciando sesión…',
    'auth.signIn.forgotPassword': '¿Olvidaste la contraseña?',
    'auth.signIn.noAccount': '¿No tienes cuenta?',
    'auth.signIn.createOne': 'Crear una',
    'auth.signIn.errorInvalid': 'Correo o contraseña incorrectos. Comprueba tus datos e inténtalo de nuevo.',
    'auth.signIn.errorNetwork': 'Error de red. Comprueba tu conexión e inténtalo de nuevo.',
    'auth.signIn.errorGeneric': 'Ha ocurrido un error al iniciar sesión. Inténtalo de nuevo.',
    'auth.signIn.errorConnect': 'No se puede conectar al servidor. Comprueba tu conexión.',
    'auth.signIn.errorUnexpected': 'Ha ocurrido un error inesperado. Inténtalo de nuevo.',
    'auth.signIn.loading': 'Cargando…',
    'auth.signIn.configError': 'Error de configuración: falta la URL de Supabase. Revisa tu archivo .env.local.',

    'auth.signUp.title': 'Crear cuenta',
    'auth.signUp.titleConfirm': 'Revisa tu correo',
    'auth.signUp.subtitle': 'Empieza tu camino hacia una mejor salud en turnos.',
    'auth.signUp.email': 'Correo electrónico',
    'auth.signUp.password': 'Contraseña',
    'auth.signUp.passwordHint': 'Mínimo 6 caracteres',
    'auth.signUp.submit': 'Registrarse',
    'auth.signUp.busy': 'Creando…',
    'auth.signUp.hasAccount': '¿Ya tienes cuenta?',
    'auth.signUp.signIn': 'Iniciar sesión',
    'auth.signUp.confirmTitle': '¡Correo de confirmación enviado!',
    'auth.signUp.confirmBody': 'Revisa tu correo y haz clic en el enlace para continuar. Serás redirigido a configurar tu perfil.',
    'auth.signUp.noEmail': '¿No recibiste el correo? Revisa la carpeta de spam o',
    'auth.signUp.tryAgain': 'inténtalo de nuevo',
    'auth.signUp.alreadyConfirmed': '¿Ya confirmaste? Iniciar sesión',
    'auth.signUp.loading': 'Preparando registro…',

    'onboarding.title': 'Bienvenido a ShiftCoach',
    'onboarding.subtitle': 'Configura tu perfil',
    'onboarding.stepOf': 'Paso {step} de {total}',
    'onboarding.name': 'Nombre',
    'onboarding.namePlaceholder': 'Introduce tu nombre',
    'onboarding.gender': 'Género',
    'onboarding.male': 'Hombre',
    'onboarding.female': 'Mujer',
    'onboarding.other': 'Otro',
    'onboarding.dateOfBirth': 'Fecha de nacimiento',
    'onboarding.optional': '(opcional)',
    'onboarding.age': 'Edad',
    'onboarding.agePlaceholder': 'Introduce tu edad',
    'onboarding.dobHint': 'Debes tener al menos 13 años',
    'onboarding.ageRange': 'Entre 13 y 120',
    'onboarding.validation.ageRange': 'La edad debe estar entre 13 y 120',
    'onboarding.validation.dobMin': 'Debes tener al menos 13 años',
    'onboarding.validation.ageMin': 'La edad debe ser al menos 13',
    'onboarding.validation.ageMax': 'La edad debe ser 120 o menos',
    'onboarding.validation.ageMismatch': "La edad no coincide con la fecha de nacimiento (debería ser unos {age})",
    'onboarding.units': 'Unidades de medida',
    'onboarding.metric': 'Métrico (cm, kg)',
    'onboarding.imperial': 'Imperial (ft/in)',
    'onboarding.heightCm': 'Altura (cm)',
    'onboarding.heightCmPlaceholder': '175',
    'onboarding.height': 'Altura',
    'onboarding.feet': 'Pies',
    'onboarding.inches': 'Pulgadas',
    'onboarding.weight': 'Peso',
    'onboarding.stone': 'Stone',
    'onboarding.pounds': 'Libras',
    'onboarding.validation.heightCm': 'La altura debe estar entre 100 cm y 250 cm',
    'onboarding.validation.heightCmHint': 'Introduce tu altura en centímetros',
    'onboarding.validation.heightBoth': 'Introduce pies y pulgadas',
    'onboarding.validation.heightRange': 'La altura debe estar entre 3 ft 3 in y 8 ft 2 in',
    'onboarding.validation.heightHint': 'Introduce tu altura en pies y pulgadas',
    'onboarding.validation.weightRange': 'El peso debe estar entre 30 kg y 300 kg (66–660 lb)',
    'onboarding.validation.weightKg': 'El peso debe estar entre 30 kg y 300 kg',
    'onboarding.validation.weightLb': 'El peso debe estar entre 66 lb y 660 lb',
    'onboarding.goal': 'Objetivo',
    'onboarding.lose': 'Perder',
    'onboarding.maintain': 'Mantener',
    'onboarding.gain': 'Ganar',
    'onboarding.sleepGoal': 'Objetivo de sueño (horas)',
    'onboarding.validation.sleepRange': 'El sueño debe estar entre 4 y 12 horas',
    'onboarding.sleepHint': 'Recomendado: 7–9 horas para adultos',
    'onboarding.waterGoal': 'Objetivo de agua (L)',
    'onboarding.validation.waterRange': 'El agua debe estar entre 1,0 L y 5,0 L',
    'onboarding.waterHint': 'Recomendado: 2,0–3,0 L al día según guías científicas',
    'onboarding.back': 'Atrás',
    'onboarding.continue': 'Continuar',
    'onboarding.complete': 'Completar configuración',
    'onboarding.saving': 'Guardando…',
    'onboarding.loading': 'Cargando…',
    'onboarding.saveFailed': 'Error al guardar el perfil',
    'onboarding.networkError': 'Error de red. Comprueba tu conexión.',

    'welcome.title': 'Tu plan está listo',
    'welcome.subtitle': 'Según tu perfil, objetivos y patrón de turnos.',
    'welcome.personalisedTarget': 'Objetivo diario personalizado',
    'welcome.kcalPerDay': 'kcal / día',
    'welcome.basedOn': 'Según tu altura, peso, edad, objetivo y el desgaste del trabajo por turnos, ShiftCoach recomienda para',
    'welcome.standardWouldGive': 'Una calculadora estándar te daría unos',
    'welcome.weAdjusted': 'Lo hemos ajustado en',
    'welcome.forPatterns': 'por tu sueño, turnos y patrones recientes.',
    'welcome.shiftAdjustedCalories': 'Calorías según turnos',
    'welcome.shiftAdjustedCaloriesDesc': 'Diseñado para turnos rotativos de día, noche y rachas largas.',
    'welcome.timingAware': 'Consciente del horario',
    'welcome.timingAwareDesc': 'Ajustamos más calorías en las partes del turno que más lo necesitan.',
    'welcome.hydrationGuidance': 'Guía de hidratación',
    'welcome.hydrationGuidanceDesc': 'Objetivos de agua adaptados a turnos largos y nocturnos.',
    'welcome.nextStep': "Siguiente: ver el plan de hoy con horarios de comidas, macros y curva de energía.",
    'welcome.continueToDashboard': 'Ir al panel',
    'welcome.loading': 'Cargando...',
    'welcome.todayNight': 'Turno de noche de esta noche',
    'welcome.todayOff': 'Hoy (día libre)',
    'welcome.todayDay': 'Turno de día de hoy',
    'welcome.today': 'Hoy',

    'dashboard.loading': 'Preparando tu panel de ShiftCoach…',
    'dashboard.homeLabel': 'Inicio',
    'dashboard.wearable.connected': 'Conectado',
    'dashboard.wearable.notConnected': 'No conectado',
    'dashboard.wearable.tapToConnect': 'Toca para conectar',
    'dashboard.wearable.syncing': 'Sincronizando…',
    'dashboard.wearable.synced': 'Sincronizado',
    'dashboard.wearable.errorDenied': 'Conexión denegada',
    'dashboard.wearable.errorServer': 'Servidor no configurado',
    'dashboard.wearable.errorRedirect': 'URI de redirección no coincide',
    'dashboard.wearable.errorToken': 'Error al intercambiar token',
    'dashboard.wearable.errorGeneric': 'No se pudo conectar',
    'dashboard.bodyClock.comingSoon': 'Puntuación del reloj corporal próximamente',
    'dashboard.bodyClock.stronglyAligned': 'Tu reloj corporal está muy alineado',
    'dashboard.bodyClock.inSync': 'Tu reloj corporal está en sincronía',
    'dashboard.bodyClock.slightlyOut': 'Tu reloj corporal está un poco desincronizado',
    'dashboard.bodyClock.outOfSync': 'Tu reloj corporal está desincronizado',
    'dashboard.bodyClock.unlockHint': 'Registra algunas noches de sueño y añade tus turnos para desbloquear la puntuación del reloj corporal.',
    'dashboard.bodyClock.calculatedFrom': 'Calculado según tu sueño reciente, patrón de turnos y luz en los últimos días.',
    'dashboard.bodyClock.openAria': 'Abrir página Reloj corporal',
    'dashboard.lastSync.notYet': 'Última sincronización: aún no',
    'dashboard.lastSync.justNow': 'Última sincronización: hace un momento',
    'dashboard.lastSync.minAgo': 'Última sincronización: hace {n} min',
    'dashboard.lastSync.hAgo': 'Última sincronización: hace {n} h',
    'dashboard.lastSync.dayAgo': 'Última sincronización: hace {n} día',
    'dashboard.lastSync.daysAgo': 'Última sincronización: hace {n} días',
    'dashboard.shiftLabel.night': 'Turno de noche',
    'dashboard.shiftLabel.day': 'Turno de día',
    'dashboard.shiftLabel.dayOff': 'Día libre',
    'dashboard.shiftLabel.late': 'Turno tardío',
    'dashboard.shiftLabel.shift': 'Turno',
    'dashboard.rhythm': 'Ritmo',
    'dashboard.recovery.calculating': 'Calculando recuperación…',
    'dashboard.recovery.calculatingMessage': 'Combinamos tu último sueño y movimiento para puntuar tu recuperación de hoy.',
    'dashboard.recovery.unavailable': 'Puntuación de recuperación no disponible',
    'dashboard.recovery.notScored': 'Recuperación aún no puntuada',
    'dashboard.recovery.notScoredMessage': 'Registra sueño y sincroniza tus wearables para ver aquí la puntuación diaria de recuperación.',
    'dashboard.recovery.recovered': 'Recuperado',
    'dashboard.recovery.recoveredMessage': 'El sueño y el movimiento apoyan la recuperación hoy; es un buen día para turnos duros o entrenar.',
    'dashboard.recovery.okNotCharged': 'Bien, no del todo cargado',
    'dashboard.recovery.okMessage': 'No estás vacío, pero algo bajo de recuperación. Protege el sueño esta noche y mantén la actividad moderada.',
    'dashboard.recovery.runningLow': 'Bajo',
    'dashboard.recovery.runningLowMessage': 'La recuperación está baja: prioriza el sueño, turnos más ligeros si puedes y evita noches seguidas.',
    'dashboard.shiftLag.low': 'Bajo',
    'dashboard.shiftLag.mod': 'Mod',
    'dashboard.shiftLag.high': 'Alto',
    'dashboard.shiftLag.per100': '/100',
    'dashboard.mealTimes.title': 'Horarios de comidas',
    'dashboard.mealTimes.night': 'Noche',
    'dashboard.mealTimes.day': 'Día',
    'dashboard.mealTimes.late': 'Tarde',
    'dashboard.mealTimes.off': 'Libre',
    'dashboard.mealTimes.whyAria': 'Por qué importa el horario de comidas',
    'dashboard.mealTimes.closeAria': 'Cerrar',
    'dashboard.mealTimes.closeStatus': 'Cerca',
    'dashboard.mealTimes.whyTitle': 'Por qué importa el horario de comidas',
    'dashboard.mealTimes.notLogged': 'No registrado',
    'dashboard.mealTimes.onTime': 'A tiempo',
    'dashboard.mealTimes.logged': 'Registrado',
    'dashboard.bodyClockInfo.title': 'Cómo funciona la puntuación del reloj corporal',
    'dashboard.bodyClockInfo.closeAria': 'Cerrar información del reloj corporal',

    'detail.common.backToDashboard': 'Volver al panel',
    'detail.common.loading': 'Cargando…',
    'detail.common.noData': 'Sin datos',
    'detail.common.disclaimer': 'Solo una app de coaching; no sustituye el consejo médico. Consulta a un profesional de la salud sobre cualquier duda.',
    'detail.common.goToDashboard': 'Ir al panel',
    'detail.bodyClock.title': 'Reloj corporal',
    'detail.bodyClock.scoreLabel': 'Puntuación del reloj corporal',
    'detail.bodyClock.overLast7': 'Reloj corporal últimos 7 días',
    'detail.bodyClock.higherBars': 'Barras más altas = días en los que tu reloj corporal estuvo más en ritmo con tus turnos.',
    'detail.bodyClock.patternVsRecovery': 'Patrón de turnos vs recuperación',
    'detail.bodyClock.patternStable': 'Patrón: mayormente estable',
    'detail.bodyClock.patternHeavy': 'Patrón: semana de mucha carga',
    'detail.bodyClock.patternChoppy': 'Patrón: semana irregular',
    'detail.bodyClock.patternMixed': 'Patrón: mixto',
    'detail.bodyClock.patternExplanation': 'Analiza cuántos días tu puntuación del reloj corporal bajó del rango en sincronía. Rachas de noches, turnos muy seguidos o desplazamientos largos pueden bajar varios días seguidos.',
    'detail.bodyClock.sleepTiming': 'Regularidad del sueño',
    'detail.bodyClock.timingNoData': 'Aún no hay suficientes datos de horarios de sueño.',
    'detail.bodyClock.timingRegular': 'Tu sueño principal ha sido bastante regular esta semana.',
    'detail.bodyClock.timingShifting': 'Los horarios de sueño varían; vigila fines tarde y madrugadas muy juntas.',
    'detail.bodyClock.timingFlipped': 'Los horarios de sueño han estado invertidos o muy irregulares; tu reloj corporal trabaja duro para seguir los turnos.',
    'detail.bodyClock.timingTip': 'Intenta mantener al menos 3 noches seguidas con horarios de sueño similares en días libres para que tu reloj corporal se recupere entre rachas de turnos.',
    'detail.bodyClock.lightHabits': 'Hábitos de luz que protegen tu reloj',
    'detail.bodyClock.lightDay': 'Turnos de día: intenta 15–20 min de luz exterior la mayoría de los días.',
    'detail.bodyClock.lightNight': 'Turnos de noche: gafas de sol al volver a casa y dormitorio a oscuras.',
    'detail.bodyClock.lightEvening': 'Noches libres: pantallas y luces tenues 1–2 h antes de dormir.',
    'detail.bodyClock.riskWindow': 'Ventana de riesgo próxima',
    'detail.bodyClock.riskWindowText': 'Según el patrón de esta semana, tu reloj corporal sufrirá más con rachas de noches, madrugadas y turnos muy seguidos. Trata los días después de esos bloques como recuperación: protege el sueño, cafeína temprano y comidas ligeras de noche.',
    'detail.bodyClock.waitingData': 'Esperando suficientes datos de sueño y turnos para mostrar la tendencia de 7 días.',
    'detail.bodyClock.warningMixed': 'Semana mixta; vigila rachas de noches y sueños muy cortos.',
    'detail.bodyClock.warningStable': 'Tu reloj corporal se ha mantenido en ritmo esta semana; sigue protegiendo los días de recuperación.',
    'detail.bodyClock.warningOutOfSync': 'Tu reloj corporal ha estado desincronizado la mayoría de los días; trata los próximos días como recuperación y revisa tu patrón de turnos.',
    'detail.bodyClock.warningQuiteFew': 'Varios días fuera de ritmo; vigila rachas de noches, madrugadas y sueño fragmentado.',

    'detail.shiftRhythm.title': 'Ritmo de turnos',
    'detail.adjustedCalories.title': 'Calorías ajustadas',
    'detail.heartHealth.title': 'Salud cardíaca',
    'detail.hydration.title': 'Hidratación',
    'detail.bingeRisk.title': 'Riesgo de atracón',
    'detail.shiftLag.title': 'Desfase de turnos',
    'detail.recovery.title': 'Puntuación de recuperación',
    'detail.recovery.subtitle': 'Qué tan listos están tu cuerpo y mente para tu próximo turno',
    'detail.wearablesSetup.title': 'Conectar tu wearable',
    'detail.wearablesSetup.howReadsData': 'Cómo ShiftCoach lee tus datos',
    'detail.wearablesSetup.intro1': "ShiftCoach no se comunica directamente con tu reloj. Lee pasos, sueño y actividad de la app de salud de tu móvil a la que tu reloj ya se sincroniza.",
    'detail.wearablesSetup.intro2': 'Elige tu dispositivo abajo y te mostraremos pasos concretos para configurarlo.',
    'detail.wearablesSetup.appleWatch': 'Apple Watch',
    'detail.wearablesSetup.appleWatchDesc': 'Usa Apple Health en tu iPhone',
    'detail.wearablesSetup.samsungAndroid': 'Reloj Samsung / Android',
    'detail.wearablesSetup.samsungAndroidDesc': 'Usa Samsung Health + Health Connect',
    'detail.wearablesSetup.otherWearable': 'Otro wearable (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherWearableDesc': 'Por ahora, conéctalo desde las apps de salud de tu móvil',
    'detail.wearablesSetup.stepsApple': 'Pasos para Apple Watch',
    'detail.wearablesSetup.appleStep1': 'Asegúrate de que el reloj está emparejado con tu iPhone y que Apple Health está activado en la app Reloj.',
    'detail.wearablesSetup.appleStep2': 'Abre la app Salud en el móvil y comprueba que muestra tus pasos y sueño.',
    'detail.wearablesSetup.appleStep3': 'En ShiftCoach, ve a Ajustes → Sincronizar wearables (o el botón de sincronizar en la pantalla principal) y sigue los pasos cuando aparezca "Conectar Apple Health".',
    'detail.wearablesSetup.appleBeta': 'En la beta actual, los datos de Apple Watch aparecerán cuando el soporte HealthKit esté activado en la versión de ShiftCoach de la App Store.',
    'detail.wearablesSetup.stepsSamsung': 'Pasos para relojes Samsung / Android',
    'detail.wearablesSetup.samsungStep1': 'Abre Samsung Health en el móvil y ve a Ajustes → Servicios conectados.',
    'detail.wearablesSetup.samsungStep2': 'Conecta Health Connect y activa la sincronización de pasos (y sueño si está disponible).',
    'detail.wearablesSetup.samsungStep3': 'Comprueba que la app de tu reloj (por ejemplo Samsung Health) comparte actividad con Health Connect.',
    'detail.wearablesSetup.samsungStep4': 'En ShiftCoach, pulsa el botón "Sincronizar wearables" en el panel e inicia sesión con la misma cuenta de Google.',
    'detail.wearablesSetup.samsungDone': 'Hecho esto, ShiftCoach obtendrá automáticamente tus pasos y sueño de Health Connect al abrir la app.',
    'detail.wearablesSetup.otherTitle': 'Otros wearables (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherP1': 'En futuras versiones añadiremos conexiones directas para más marcas. Por ahora, la forma más fácil es sincronizar el dispositivo con Apple Health o Health Connect en el móvil y dejar que ShiftCoach lea desde ahí.',
    'detail.wearablesSetup.otherP2': 'Muchas apps (incluidas Fitbit y Garmin) pueden escribir pasos y sueño en estos hubs de salud desde su propia configuración.',
    'detail.wearablesSetup.whatYouGet': 'Qué obtienes al conectarlo',
    'detail.wearablesSetup.benefit1': 'Pasos y movimiento automáticos en tu pantalla de inicio y en la página de Actividad.',
    'detail.wearablesSetup.benefit2': 'Puntuaciones de sueño y Shift Lag más precisas basadas en noches reales, no estimaciones.',
    'detail.wearablesSetup.benefit3': 'Mejores objetivos de calorías y recuperación según la carga real de tus turnos.',
    'detail.wearablesSetup.readyToSync': '¿Listo para sincronizar tu wearable?',
    'detail.wearablesSetup.tapBelow': 'Pulsa abajo después de seguir los pasos de tu dispositivo.',
    'detail.wearablesSetup.statusConnected': 'Wearable conectado',
    'detail.wearablesSetup.statusConnectedDesc': 'Tu wearable está vinculado. Pulsa sincronizar para obtener los últimos pasos y sueño.',
    'detail.wearablesSetup.verifiedWorking': 'Conexión verificada: los datos de tu reloj llegan a ShiftCoach.',
    'detail.wearablesSetup.stepsToday': 'Pasos hoy: {count}',
    'detail.wearablesSetup.verifiedConfirmation': 'Tu wearable está conectado y funcionando. Los pasos y el sueño aparecerán en el panel tras sincronizar.',
    'detail.wearablesSetup.statusNotConnected': 'Wearable no conectado',
    'detail.wearablesSetup.notConnectedWhy': 'ShiftCoach necesita acceso al wearable para leer pasos y sueño. Conecta Samsung Health (o la app de tu reloj) con Health Connect en Android, o Apple Health en iPhone.',
    'detail.wearablesSetup.connectGoogleFit': 'Abrir configuración de wearable',
  },
  de: {
    'nav.home': 'Start',
    'nav.calendar': 'Dienstplan',
    'nav.blog': 'Blog',
    'nav.browse': 'Entdecken',
    'nav.profile': 'Profil',

    'browse.title': 'Entdecken',
    'browse.subtitle': 'Schnell zu den wichtigsten Werkzeugen.',
    'browse.sleepLog.title': 'Schlafprotokoll',
    'browse.sleepLog.desc': 'Sieh und bearbeite deinen letzten Schlaf.',
    'browse.activity.title': 'Aktivität',
    'browse.activity.desc': 'Erfasse Schritte und Aktivität für deine Schichten.',
    'browse.shiftCoach.title': 'Shift Coach',
    'browse.shiftCoach.desc': 'Frag den KI‑Coach nach persönlichen Tipps.',
    'browse.settings.title': 'Einstellungen',
    'browse.settings.desc': 'Profil, Einheiten und App‑Einstellungen anpassen.',
    'browse.wearables.title': 'Wearables',
    'browse.wearables.desc': 'Verbinde deine Apple‑ oder Samsung‑Uhr.',
    'browse.feedback.title': 'Problem melden',
    'browse.feedback.desc': 'Feedback senden oder Fehler melden.',

    'settings.title': 'Einstellungen',
    'settings.section.account': 'Konto',
    'settings.section.preferences': 'Präferenzen',
    'settings.section.coaching': 'Coaching',
    'settings.section.support': 'Support',

    'settings.language.title': 'Sprache',
    'settings.language.device': 'Sprache des Geräts verwenden',
    'settings.language.en': 'Englisch',
    'settings.language.es': 'Spanisch',
    'settings.language.de': 'Deutsch',

    'splash.tagline': 'Die einzige App für Gesundheit und Wohlbefinden von Schichtarbeitern',
    'splash.audience': 'Für Pflegekräfte, Rettungssanitäter, Wachleute, Köche und Operatoren.',
    'splash.preparing': 'Dein Schichtplan wird vorbereitet…',
    'splash.imageAlt': 'Gruppe von Schichtarbeitern',

    'auth.tagline': 'Für die Gesundheit von Schichtarbeitern.',
    'auth.personalized': 'An deine Schichten angepasst',
    'auth.signIn.title': 'Willkommen zurück',
    'auth.signIn.subtitle': 'Melde dich an, um deinen Plan fortzusetzen.',
    'auth.signIn.email': 'E-Mail',
    'auth.signIn.password': 'Passwort',
    'auth.signIn.submit': 'Anmelden',
    'auth.signIn.busy': 'Anmeldung…',
    'auth.signIn.forgotPassword': 'Passwort vergessen?',
    'auth.signIn.noAccount': 'Noch kein Konto?',
    'auth.signIn.createOne': 'Konto erstellen',
    'auth.signIn.errorInvalid': 'Ungültige E-Mail oder Passwort. Bitte prüfe deine Angaben.',
    'auth.signIn.errorNetwork': 'Netzwerkfehler. Bitte prüfe deine Internetverbindung.',
    'auth.signIn.errorGeneric': 'Bei der Anmeldung ist ein Fehler aufgetreten. Bitte versuche es erneut.',
    'auth.signIn.errorConnect': 'Verbindung zum Server nicht möglich. Bitte prüfe deine Internetverbindung.',
    'auth.signIn.errorUnexpected': 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut.',
    'auth.signIn.loading': 'Laden…',
    'auth.signIn.configError': 'Konfigurationsfehler: Supabase-URL fehlt. Bitte .env.local prüfen.',

    'auth.signUp.title': 'Konto erstellen',
    'auth.signUp.titleConfirm': 'E-Mail prüfen',
    'auth.signUp.subtitle': 'Starte deinen Weg zu besserer Schichtarbeitergesundheit.',
    'auth.signUp.email': 'E-Mail',
    'auth.signUp.password': 'Passwort',
    'auth.signUp.passwordHint': 'Mindestens 6 Zeichen',
    'auth.signUp.submit': 'Registrieren',
    'auth.signUp.busy': 'Wird erstellt…',
    'auth.signUp.hasAccount': 'Bereits ein Konto?',
    'auth.signUp.signIn': 'Anmelden',
    'auth.signUp.confirmTitle': 'Bestätigungs-E-Mail gesendet!',
    'auth.signUp.confirmBody': 'Bitte prüfe deine E-Mail und klicke auf den Link. Du wirst zur Profil-Einrichtung weitergeleitet.',
    'auth.signUp.noEmail': 'E-Mail nicht erhalten? Prüfe den Spam-Ordner oder',
    'auth.signUp.tryAgain': 'nochmal versuchen',
    'auth.signUp.alreadyConfirmed': 'Bereits bestätigt? Anmelden',
    'auth.signUp.loading': 'Registrierung wird vorbereitet…',

    'onboarding.title': 'Willkommen bei ShiftCoach',
    'onboarding.subtitle': 'Richte dein Profil ein',
    'onboarding.stepOf': 'Schritt {step} von {total}',
    'onboarding.name': 'Name',
    'onboarding.namePlaceholder': 'Dein Name',
    'onboarding.gender': 'Geschlecht',
    'onboarding.male': 'Männlich',
    'onboarding.female': 'Weiblich',
    'onboarding.other': 'Divers',
    'onboarding.dateOfBirth': 'Geburtsdatum',
    'onboarding.optional': '(optional)',
    'onboarding.age': 'Alter',
    'onboarding.agePlaceholder': 'Dein Alter',
    'onboarding.dobHint': 'Du musst mindestens 13 Jahre alt sein',
    'onboarding.ageRange': 'Zwischen 13 und 120',
    'onboarding.validation.ageRange': 'Alter muss zwischen 13 und 120 liegen',
    'onboarding.validation.dobMin': 'Du musst mindestens 13 Jahre alt sein',
    'onboarding.validation.ageMin': 'Alter muss mindestens 13 sein',
    'onboarding.validation.ageMax': 'Alter darf höchstens 120 sein',
    'onboarding.validation.ageMismatch': 'Alter passt nicht zum Geburtsdatum (sollte etwa {age} sein)',
    'onboarding.units': 'Maßeinheiten',
    'onboarding.metric': 'Metrisch (cm, kg)',
    'onboarding.imperial': 'Imperial (ft/in)',
    'onboarding.heightCm': 'Größe (cm)',
    'onboarding.heightCmPlaceholder': '175',
    'onboarding.height': 'Größe',
    'onboarding.feet': 'Fuß',
    'onboarding.inches': 'Zoll',
    'onboarding.weight': 'Gewicht',
    'onboarding.stone': 'Stone',
    'onboarding.pounds': 'Pfund',
    'onboarding.validation.heightCm': 'Größe muss zwischen 100 cm und 250 cm liegen',
    'onboarding.validation.heightCmHint': 'Größe in Zentimetern eingeben',
    'onboarding.validation.heightBoth': 'Bitte Fuß und Zoll eingeben',
    'onboarding.validation.heightRange': 'Größe muss zwischen 3 ft 3 in und 8 ft 2 in liegen',
    'onboarding.validation.heightHint': 'Größe in Fuß und Zoll eingeben',
    'onboarding.validation.weightRange': 'Gewicht muss zwischen 30 kg und 300 kg (66–660 lb) liegen',
    'onboarding.validation.weightKg': 'Gewicht muss zwischen 30 kg und 300 kg liegen',
    'onboarding.validation.weightLb': 'Gewicht muss zwischen 66 lb und 660 lb liegen',
    'onboarding.goal': 'Ziel',
    'onboarding.lose': 'Abnehmen',
    'onboarding.maintain': 'Halten',
    'onboarding.gain': 'Zunehmen',
    'onboarding.sleepGoal': 'Schlafziel (Stunden)',
    'onboarding.validation.sleepRange': 'Schlafziel muss zwischen 4 und 12 Stunden liegen',
    'onboarding.sleepHint': 'Empfohlen: 7–9 Stunden für Erwachsene',
    'onboarding.waterGoal': 'Wasserziel (L)',
    'onboarding.validation.waterRange': 'Wasserziel muss zwischen 1,0 L und 5,0 L liegen',
    'onboarding.waterHint': 'Empfohlen: 2,0–3,0 L pro Tag nach wissenschaftlichen Leitlinien',
    'onboarding.back': 'Zurück',
    'onboarding.continue': 'Weiter',
    'onboarding.complete': 'Einrichtung abschließen',
    'onboarding.saving': 'Wird gespeichert…',
    'onboarding.loading': 'Laden…',
    'onboarding.saveFailed': 'Profil konnte nicht gespeichert werden',
    'onboarding.networkError': 'Netzwerkfehler. Bitte Verbindung prüfen.',

    'welcome.title': 'Dein Plan ist fertig',
    'welcome.subtitle': 'Basierend auf deinem Profil, Zielen und Schichtmuster.',
    'welcome.personalisedTarget': 'Personalisierte Tagesziel',
    'welcome.kcalPerDay': 'kcal / Tag',
    'welcome.basedOn': 'Basierend auf Größe, Gewicht, Alter, Ziel und Schichtarbeit empfiehlt ShiftCoach für',
    'welcome.standardWouldGive': 'Ein Standardrechner würde etwa',
    'welcome.weAdjusted': 'Wir haben um',
    'welcome.forPatterns': 'für Schlaf, Schichten und Muster angepasst.',
    'welcome.shiftAdjustedCalories': 'Schicht-angepasste Kalorien',
    'welcome.shiftAdjustedCaloriesDesc': 'Speziell für wechselnde Tage-, Nacht- und Langschichten.',
    'welcome.timingAware': 'Zeitbewusst',
    'welcome.timingAwareDesc': 'Mehr Kalorien in die Phasen deiner Schicht, die sie brauchen.',
    'welcome.hydrationGuidance': 'Hydratationshinweise',
    'welcome.hydrationGuidanceDesc': 'Tägliche Wasserziele für lange und Nachtschichten.',
    'welcome.nextStep': "Als Nächstes: heutigen Plan mit Mahlzeiten, Makros und Energieverlauf ansehen.",
    'welcome.continueToDashboard': 'Zum Dashboard',
    'welcome.loading': 'Laden...',
    'welcome.todayNight': 'Heutige Nachtschicht',
    'welcome.todayOff': 'Heute (frei)',
    'welcome.todayDay': 'Heutige Tagesschicht',
    'welcome.today': 'Heute',

    'dashboard.loading': 'ShiftCoach-Dashboard wird vorbereitet…',
    'dashboard.homeLabel': 'Start',
    'dashboard.wearable.connected': 'Verbunden',
    'dashboard.wearable.notConnected': 'Nicht verbunden',
    'dashboard.wearable.tapToConnect': 'Tippen zum Verbinden',
    'dashboard.wearable.syncing': 'Wird synchronisiert…',
    'dashboard.wearable.synced': 'Synchronisiert',
    'dashboard.wearable.errorDenied': 'Verbindung abgelehnt',
    'dashboard.wearable.errorServer': 'Server nicht konfiguriert',
    'dashboard.wearable.errorRedirect': 'Redirect-URI stimmt nicht überein',
    'dashboard.wearable.errorToken': 'Token-Austausch fehlgeschlagen',
    'dashboard.wearable.errorGeneric': 'Verbindung fehlgeschlagen',
    'dashboard.bodyClock.comingSoon': 'Body-Clock-Score demnächst',
    'dashboard.bodyClock.stronglyAligned': 'Deine Körperuhr ist stark im Einklang',
    'dashboard.bodyClock.inSync': 'Deine Körperuhr ist im Takt',
    'dashboard.bodyClock.slightlyOut': 'Deine Körperuhr ist leicht verschoben',
    'dashboard.bodyClock.outOfSync': 'Deine Körperuhr ist aus dem Takt',
    'dashboard.bodyClock.unlockHint': 'Trage ein paar Nächte Schlaf ein und füge deine Schichten hinzu, um den Body-Clock-Score zu entsperren.',
    'dashboard.bodyClock.calculatedFrom': 'Berechnet aus deinem letzten Schlaf, Schichtmuster und Licht der letzten Tage.',
    'dashboard.bodyClock.openAria': 'Body-Clock-Seite öffnen',
    'dashboard.lastSync.notYet': 'Letzte Sync: noch nicht',
    'dashboard.lastSync.justNow': 'Letzte Sync: gerade eben',
    'dashboard.lastSync.minAgo': 'Letzte Sync: vor {n} Min.',
    'dashboard.lastSync.hAgo': 'Letzte Sync: vor {n} Std.',
    'dashboard.lastSync.dayAgo': 'Letzte Sync: vor {n} Tag',
    'dashboard.lastSync.daysAgo': 'Letzte Sync: vor {n} Tagen',
    'dashboard.shiftLabel.night': 'Nachtschicht',
    'dashboard.shiftLabel.day': 'Tagesschicht',
    'dashboard.shiftLabel.dayOff': 'Frei',
    'dashboard.shiftLabel.late': 'Spätschicht',
    'dashboard.shiftLabel.shift': 'Schicht',
    'dashboard.rhythm': 'Rhythmus',
    'dashboard.recovery.calculating': 'Erholung wird berechnet…',
    'dashboard.recovery.calculatingMessage': 'Wir werten deinen letzten Schlaf und Bewegung aus, um deine Erholung für heute zu berechnen.',
    'dashboard.recovery.unavailable': 'Erholungswert nicht verfügbar',
    'dashboard.recovery.notScored': 'Erholung noch nicht bewertet',
    'dashboard.recovery.notScoredMessage': 'Trage Schlaf ein und synchronisiere deine Wearables, um hier einen täglichen Erholungswert zu sehen.',
    'dashboard.recovery.recovered': 'Erholt',
    'dashboard.recovery.recoveredMessage': 'Schlaf und Bewegung unterstützen die Erholung heute – ein guter Tag für harte Schichten oder Training.',
    'dashboard.recovery.okNotCharged': 'OK, nicht voll aufgeladen',
    'dashboard.recovery.okMessage': 'Du läufst nicht leer, aber etwas untererholt. Schütze den Schlaf heute Nacht und halte die Aktivität moderat.',
    'dashboard.recovery.runningLow': 'Niedrig',
    'dashboard.recovery.runningLowMessage': 'Erholung ist niedrig – priorisiere Schlaf, leichtere Schichten wo möglich und vermeide viele Nachtschichten hintereinander.',
    'dashboard.shiftLag.low': 'Niedrig',
    'dashboard.shiftLag.mod': 'Mod',
    'dashboard.shiftLag.high': 'Hoch',
    'dashboard.shiftLag.per100': '/100',
    'dashboard.mealTimes.title': 'Mahlzeitenzeiten',
    'dashboard.mealTimes.night': 'Nacht',
    'dashboard.mealTimes.day': 'Tag',
    'dashboard.mealTimes.late': 'Spät',
    'dashboard.mealTimes.off': 'Frei',
    'dashboard.mealTimes.whyAria': 'Warum Mahlzeitenzeiten wichtig sind',
    'dashboard.mealTimes.closeAria': 'Schließen',
    'dashboard.mealTimes.closeStatus': 'Knapp',
    'dashboard.mealTimes.whyTitle': 'Warum Mahlzeitenzeiten wichtig sind',
    'dashboard.mealTimes.notLogged': 'Nicht erfasst',
    'dashboard.mealTimes.onTime': 'Pünktlich',
    'dashboard.mealTimes.logged': 'Erfasst',
    'dashboard.bodyClockInfo.title': 'So funktioniert dein Body-Clock-Score',
    'dashboard.bodyClockInfo.closeAria': 'Body-Clock-Info schließen',

    'detail.common.backToDashboard': 'Zurück zum Dashboard',
    'detail.common.loading': 'Laden…',
    'detail.common.noData': 'Keine Daten',
    'detail.common.disclaimer': 'Nur eine Coaching-App, ersetzt keine medizinische Beratung. Bitte sprich bei gesundheitlichen Fragen mit einem Arzt.',
    'detail.common.goToDashboard': 'Zum Dashboard',
    'detail.bodyClock.title': 'Körperuhr',
    'detail.bodyClock.scoreLabel': 'Body-Clock-Score',
    'detail.bodyClock.overLast7': 'Körperuhr letzte 7 Tage',
    'detail.bodyClock.higherBars': 'Höhere Balken = Tage, an denen deine Körperuhr eher im Takt mit deinen Schichten war.',
    'detail.bodyClock.patternVsRecovery': 'Schichtmuster vs. Erholung',
    'detail.bodyClock.patternStable': 'Muster: überwiegend stabil',
    'detail.bodyClock.patternHeavy': 'Muster: anstrengende Woche',
    'detail.bodyClock.patternChoppy': 'Muster: wechselhafte Woche',
    'detail.bodyClock.patternMixed': 'Muster: gemischt',
    'detail.bodyClock.patternExplanation': 'Zeigt, an wie vielen Tagen dein Body-Clock-Score unter den Takt-Bereich gefallen ist. Nachtschichten, kurze Pausen oder lange Anfahrten können mehrere Tage hintereinander runterziehen.',
    'detail.bodyClock.sleepTiming': 'Schlafzeiten-Konstanz',
    'detail.bodyClock.timingNoData': 'Noch nicht genug Schlafzeit-Daten.',
    'detail.bodyClock.timingRegular': 'Dein Hauptschlaf war diese Woche ziemlich regelmäßig.',
    'detail.bodyClock.timingShifting': 'Die Schlafzeiten verschieben sich – achte auf späte Dienste und sehr frühe Starts nah beieinander.',
    'detail.bodyClock.timingFlipped': 'Schlafzeiten waren umgedreht oder sehr unregelmäßig – deine Körperuhr arbeitet hart, um mit den Schichten mitzuhalten.',
    'detail.bodyClock.timingTip': 'Versuche mindestens 3 Nächte hintereinander mit ähnlicher Hauptschlafzeit an freien Tagen, damit sich deine Körperuhr zwischen Schichtblöcken erholen kann.',
    'detail.bodyClock.lightHabits': 'Lichtgewohnheiten, die deine Uhr schützen',
    'detail.bodyClock.lightDay': 'Tagesschichten: 15–20 Min. Tageslicht an den meisten Tagen.',
    'detail.bodyClock.lightNight': 'Nachtschichten: Sonnenbrille auf dem Heimweg und dunkles Schlafzimmer.',
    'detail.bodyClock.lightEvening': 'Abende frei: Bildschirme und helles Licht 1–2 h vor dem Schlaf dimmen.',
    'detail.bodyClock.riskWindow': 'Kommendes Risikofenster',
    'detail.bodyClock.riskWindowText': 'Nach dem Muster dieser Woche werden Nachtschicht-Blöcke, frühe Starts und kurze Pausen deine Körperuhr am meisten belasten. Behandle die Tage danach als Erholung: Schlaf schützen, Koffein früh, leichtere Mahlzeiten nachts.',
    'detail.bodyClock.waitingData': 'Warte auf genug Schlaf- und Schichtdaten für den 7-Tage-Trend.',
    'detail.bodyClock.warningMixed': 'Gemischte Woche – achte auf Nachtschicht-Blöcke und sehr kurzen Schlaf.',
    'detail.bodyClock.warningStable': 'Deine Körperuhr war diese Woche meist im Takt – schütze weiter die Erholungstage.',
    'detail.bodyClock.warningOutOfSync': 'Deine Körperuhr war an den meisten Tagen aus dem Takt – behandle die nächsten Tage wo möglich als Erholung und prüfe dein Schichtmuster.',
    'detail.bodyClock.warningQuiteFew': 'Einige Tage außer Takt – achte auf Nachtschicht-Blöcke, frühe Starts und fragmentierten Schlaf.',

    'detail.shiftRhythm.title': 'Schichtrhythmus',
    'detail.adjustedCalories.title': 'Angepasste Kalorien',
    'detail.heartHealth.title': 'Herzgesundheit',
    'detail.hydration.title': 'Hydration',
    'detail.bingeRisk.title': 'Binge-Risiko',
    'detail.shiftLag.title': 'Schichtlag',
    'detail.recovery.title': 'Erholungswert',
    'detail.recovery.subtitle': 'Wie bereit Körper und Geist für deine nächste Schicht sind',
    'detail.wearablesSetup.title': 'Wearable verbinden',
    'detail.wearablesSetup.howReadsData': 'Wie ShiftCoach deine Daten liest',
    'detail.wearablesSetup.intro1': "ShiftCoach spricht nicht direkt mit deiner Uhr. Stattdessen liest es Schritte, Schlaf und Aktivität aus der Gesundheits-App auf deinem Handy, mit der deine Uhr bereits synchronisiert.",
    'detail.wearablesSetup.intro2': "Wähle unten dein Gerät und wir zeigen dir einfache, gerätespezifische Schritte zur Einrichtung.",
    'detail.wearablesSetup.appleWatch': 'Apple Watch',
    'detail.wearablesSetup.appleWatchDesc': 'Nutzt Apple Health auf deinem iPhone',
    'detail.wearablesSetup.samsungAndroid': 'Samsung- / Android-Uhr',
    'detail.wearablesSetup.samsungAndroidDesc': 'Nutzt Samsung Health + Health Connect',
    'detail.wearablesSetup.otherWearable': 'Anderes Wearable (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherWearableDesc': "Vorerst über die Gesundheits-Apps deines Handys verbinden",
    'detail.wearablesSetup.stepsApple': 'Schritte für Apple Watch',
    'detail.wearablesSetup.appleStep1': 'Stelle sicher, dass deine Uhr mit deinem iPhone gekoppelt ist und Apple Health in der Watch-App aktiviert ist.',
    'detail.wearablesSetup.appleStep2': 'Öffne die Health-App auf deinem Handy und prüfe, ob Schritte und Schlaf angezeigt werden.',
    'detail.wearablesSetup.appleStep3': 'In ShiftCoach: Einstellungen → Wearables synchronisieren (oder Sync-Button auf dem Startbildschirm) und die Hinweise befolgen, wenn „Apple Health verbinden“ verfügbar ist.',
    'detail.wearablesSetup.appleBeta': 'In der aktuellen Beta erscheinen Apple-Watch-Daten, sobald HealthKit-Unterstützung in der App-Store-Version von ShiftCoach aktiviert ist.',
    'detail.wearablesSetup.stepsSamsung': 'Schritte für Samsung- / Android-Uhren',
    'detail.wearablesSetup.samsungStep1': 'Öffne Samsung Health auf dem Handy und gehe zu Einstellungen → Verbundene Dienste.',
    'detail.wearablesSetup.samsungStep2': 'Verbinde Health Connect und aktiviere die Synchronisation für Schritte (und ggf. Schlaf).',
    'detail.wearablesSetup.samsungStep3': 'Stelle sicher, dass deine Uhren-App (z. B. Samsung Health) Aktivität an Health Connect weitergibt.',
    'detail.wearablesSetup.samsungStep4': 'In ShiftCoach tippe auf den Button „Wearables synchronisieren“ im Dashboard und melde dich mit demselben Google-Konto an.',
    'detail.wearablesSetup.samsungDone': 'Danach lädt ShiftCoach beim Öffnen der App automatisch Schritte und Schlaf aus Health Connect.',
    'detail.wearablesSetup.otherTitle': 'Andere Wearables (Fitbit, Garmin, etc.)',
    'detail.wearablesSetup.otherP1': 'In zukünftigen Versionen kommen direkte Anbindungen für weitere Marken. Vorerst: Gerät in Apple Health oder Health Connect auf dem Handy synchronisieren, ShiftCoach liest von dort.',
    'detail.wearablesSetup.otherP2': 'Viele Apps (u. a. Fitbit und Garmin) können in ihren Einstellungen Schritte und Schlaf in diese Gesundheits-Hubs schreiben.',
    'detail.wearablesSetup.whatYouGet': 'Was du nach der Verbindung bekommst',
    'detail.wearablesSetup.benefit1': 'Automatische Schritte und Bewegung auf Startbildschirm und Aktivitätsseite.',
    'detail.wearablesSetup.benefit2': 'Genauere Schlaf- und Shift-Lag-Scores basierend auf echten Nächten, nicht Schätzungen.',
    'detail.wearablesSetup.benefit3': 'Bessere Kalorien- und Erholungsziele, die deine tatsächliche Schichtbelastung widerspiegeln.',
    'detail.wearablesSetup.readyToSync': 'Bereit, dein Wearable zu synchronisieren?',
    'detail.wearablesSetup.tapBelow': "Tippe unten, nachdem du die Schritte für dein Gerät ausgeführt hast.",
    'detail.wearablesSetup.statusConnected': 'Wearable verbunden',
    'detail.wearablesSetup.statusConnectedDesc': 'Dein Wearable ist verbunden. Tippe auf Sync, um die neuesten Schritte und den Schlaf zu laden.',
    'detail.wearablesSetup.verifiedWorking': 'Verbindung geprüft – deine Uhrendaten erreichen ShiftCoach.',
    'detail.wearablesSetup.stepsToday': 'Schritte heute: {count}',
    'detail.wearablesSetup.verifiedConfirmation': 'Dein Wearable ist verbunden und funktioniert. Schritte und Schlaf erscheinen nach dem Sync im Dashboard.',
    'detail.wearablesSetup.statusNotConnected': 'Wearable nicht verbunden',
    'detail.wearablesSetup.notConnectedWhy': 'ShiftCoach braucht Zugriff auf dein Wearable, um Schritte und Schlaf zu lesen. Verbinde Samsung Health (oder deine Uhren-App) mit Health Connect auf Android oder nutze Apple Health auf dem iPhone.',
    'detail.wearablesSetup.connectGoogleFit': 'Wearable-Einrichtung öffnen',
  },
}

export function useTranslation() {
  const { language } = useLanguage()
  return {
    t: (key: string) => messages[language]?.[key] ?? messages.en[key] ?? key,
  }
}

